services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    environment:
      - DB_SOURCE=postgresql://default:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command:
      - "/app/main"
